version: "3.8"

services:
  hrhelper:
    image: node:20
    container_name: hrhelper
    user: "1000:1000"
    ports:
      - "8002:5173"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped
