services:
  vite-js:
    build: .
    container_name: hrtoolkit
    hostname: home
    ports:
      - "8002:80"
    restart: unless-stopped
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true
